services:
  redis:
    image: redis:7-alpine
    container_name: redis-url-audit
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: url-audit-api
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379